name: build-and-deploy-staging

on:
  push:
    branches: [master]

env:
  APP_DIR: /opt/nnp-web
  PM2_NAME: nnp-web
  NODE_VERSION: '20'
  BUILD_DIR: build
  PM2_HOME: /home/manage/.pm2
  ENV_SOURCE_DIR: /home/manage/env-nusa

jobs:
  build-deploy:
    runs-on: [self-hosted, Linux, X64, Staging]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Debug whoami & perms
        run: |
          echo "USER: $(whoami)"
          id
          ls -ld /opt /opt/nnp-web || true
          mkdir -p "$APP_DIR"
          > "$APP_DIR/.gh-actions-write-test" && echo "write ok" || { echo "::error::Cannot write to $APP_DIR"; exit 1; }

      - name: Sync to $APP_DIR (repo files)
        run: |
          set -euo pipefail
          shopt -s dotglob nullglob
          rm -rf "${APP_DIR:?}/"*
          cp -a ./* "$APP_DIR"/
          echo "Copied repo to $APP_DIR"

      # 🔁 New: bring in the PM2 ecosystem file from your env folder
      - name: Provision PM2 ecosystem file
        run: |
          set -euo pipefail
          SRC="${ENV_SOURCE_DIR}/ecosystem.config.cjs"
          echo "Using ecosystem: $SRC"
          if [ ! -f "$SRC" ]; then
            echo "::error file=$SRC::ecosystem.config.cjs not found"; exit 1;
          fi
          cp "$SRC" "$APP_DIR/ecosystem.config.cjs"
          ls -l "$APP_DIR/ecosystem.config.cjs"

      - name: Install deps (include dev)
        working-directory: ${{ env.APP_DIR }}
        run: npm ci --no-audit --no-fund

      - name: Build (Tailwind plugin in devDependencies)
        working-directory: ${{ env.APP_DIR }}
        env:
          NODE_ENV: development
        run: npm run build

      - name: Prune dev deps for runtime
        working-directory: ${{ env.APP_DIR }}
        run: npm prune --omit=dev

      - name: Ensure pm2 (local, no jq needed)
        working-directory: ${{ env.APP_DIR }}
        run: |
          if [ ! -d "node_modules/pm2" ]; then
            npm i -E pm2@latest
          fi

      # 🔁 New: use ecosystem & env_staging (pm2 --env staging)
      - name: Restart app with PM2 via ecosystem
        working-directory: ${{ env.APP_DIR }}
        env:
          PM2_HOME: ${{ env.PM2_HOME }}
        run: |
          echo "PM2_HOME=$PM2_HOME"
          npx pm2 -v || true
          # stop old instance if any
          npx pm2 delete "${PM2_NAME}" || true
          # start using the ecosystem with env_staging
          npx pm2 start ecosystem.config.cjs --env staging
          npx pm2 save
          npx pm2 status || true
